version: "3"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    networks: 
        - FetchR
    environment: 
        - CGO_ENABLED=0 
networks: 
    FetchR:
        